[package]
name = "web-app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
seed = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
string-join = "0.1.2"
wasm-bindgen = "0.2"